# Generated by Django 3.1.1 on 2020-11-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='Account_foreignkey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
