# Generated by Django 3.1.1 on 2020-11-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0002_auto_20201103_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='Account_foreignkey',
            new_name='Account',
        ),
    ]
