# Generated by Django 3.1.1 on 2020-09-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0002_profiledetail_lastactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('lastactive', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('score', models.IntegerField(max_length=100)),
                ('lastactive', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileDetail',
        ),
    ]
