# Generated by Django 3.1.1 on 2020-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0003_auto_20200930_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('lastactive', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Acount',
        ),
        migrations.RenameField(
            model_name='acountdetail',
            old_name='lastactive',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='acountdetail',
            name='bio',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='acountdetail',
            name='score',
            field=models.IntegerField(),
        ),
    ]
