# Generated by Django 3.1.1 on 2020-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0004_auto_20200930_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
