# Generated by Django 3.1.1 on 2020-12-09 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileDetails', '0004_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='id',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
