# Generated by Django 3.1.1 on 2020-09-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0005_account_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcountDetail',
            new_name='AccountDetail',
        ),
    ]
