# Generated by Django 3.1.1 on 2020-09-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0006_auto_20200930_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
