# Generated by Django 3.1.1 on 2020-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0006_auto_20201210_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='Phone',
            field=models.CharField(default=1000000000, max_length=10),
            preserve_default=False,
        ),
    ]
