# Generated by Django 3.1.1 on 2020-12-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0007_ledger_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='Phone',
            new_name='ph_num',
        ),
    ]
