# Generated by Django 3.1.1 on 2020-09-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0008_accountdetail_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='score',
            field=models.CharField(max_length=1),
        ),
    ]
