# Generated by Django 3.1.1 on 2020-09-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDetails', '0009_auto_20200930_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='Account_id',
            new_name='account',
        ),
    ]
