# Generated by Django 3.0.3 on 2020-10-11 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('msg_to', '-sent_timestamp')},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='command',
            field=models.CharField(default='receive_msg', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_from',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Message From'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_to',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Message To'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent timestamp'),
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_received_receiver', models.DateTimeField(blank=True, null=True)),
                ('last_seen_receiver', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('receiver', '-last_seen_receiver', '-last_received_receiver'),
            },
        ),
        migrations.CreateModel(
            name='ActiveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activeDetail', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue', to='chat.Dialogue', verbose_name='dialogue key'),
        ),
    ]
