# Generated by Django 3.0.3 on 2020-10-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201011_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.Dialogue', verbose_name='dialogue key'),
        ),
    ]
