# Generated by Django 3.0.3 on 2020-11-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20201024_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Group Name')),
                ('key', models.CharField(blank=True, max_length=10, null=True, verbose_name='Group Key')),
                ('bio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Group Bio')),
                ('admin', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='group admins')),
                ('participants', models.ManyToManyField(default=None, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='group participants')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_from', models.CharField(blank=True, max_length=10, null=True, verbose_name='Message From')),
                ('msg_to', models.CharField(blank=True, max_length=10, null=True, verbose_name='Message To')),
                ('message', models.CharField(max_length=1200)),
                ('command', models.CharField(default='receive_msg', max_length=20)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='sent timestamp')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.Group', verbose_name='group key')),
                ('pending', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='msg not received by')),
            ],
        ),
    ]
