# Generated by Django 3.0.3 on 2020-11-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201125_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='bio',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Group Bio'),
        ),
        migrations.AlterField(
            model_name='group',
            name='key',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='Group Key'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='msg_from',
            field=models.CharField(default=None, max_length=10, verbose_name='Message From'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='msg_to',
            field=models.CharField(default=None, max_length=10, verbose_name='Message To'),
        ),
        migrations.AlterField(
            model_name='message',
            name='dialogue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.Dialogue', verbose_name='dialogue key'),
        ),
    ]
