# Generated by Django 3.0.3 on 2020-12-01 12:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20201126_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 44, 21, 473681))),
                ('participants', models.ManyToManyField(default=None, max_length=2, to=settings.AUTH_USER_MODEL, verbose_name='room participants')),
            ],
            options={
                'ordering': ('active', '-created'),
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_from', models.CharField(blank=True, max_length=10, null=True, verbose_name='Message From')),
                ('msg_to', models.CharField(blank=True, max_length=10, null=True, verbose_name='Message To')),
                ('message', models.CharField(max_length=1200)),
                ('command', models.CharField(default='', max_length=20)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='sent timestamp')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.Room', verbose_name='room key')),
            ],
            options={
                'ordering': ('msg_to', 'msg_to', '-sent_timestamp'),
            },
        ),
    ]
