# Generated by Django 3.1.1 on 2020-12-20 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20201205_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='finished',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 16, 34, 41, 16669)),
        ),
    ]
