# Generated by Django 3.0.3 on 2020-12-16 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20201216_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='finished',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 17, 52, 35, 286755)),
        ),
    ]
