# Generated by Django 3.0.3 on 2020-12-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20201216_1752'),
        ('chat', '0009_auto_20201218_1743'),
    ]

    operations = [
    ]
