# Generated by Django 3.0.3 on 2021-01-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_merge_20201218_1758'),
        ('chat', '0009_auto_20201220_1634'),
    ]

    operations = [
    ]
