# Generated by Django 3.0.3 on 2021-01-20 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20210120_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='finished',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 16, 55, 20, 526153)),
        ),
    ]
